// GENERATED by tools/build-summary-fn.mjs from index.html — do not edit by hand.
export const PHASES = ["Pre Phase","Phase 1","Phase 2","Phase 3","Phase 4","Phase 5","Phase 6"];
export const PHASE_TASKS = {
  "Pre Phase": [
    "Open Bank Account",
    "Obtain Building Permits",
    "Obtain Builders Risk",
    "Order and Set up Sign with Address",
    "Install Camera with 4x4 12ft 2 ft in ground"
  ],
  "Phase 1": [
    "Site Layout",
    "Order Porta-Can",
    "Import Fill Dirt & Compact",
    "Excavation (Footings / Trenches / Foundation)",
    "Schedule Pre Form Survey",
    "Plumbing Rough In",
    "Footings Form & Rebar",
    "Termite Treatment",
    "Vapor Barrier Installation",
    "Electrical Rough in / Island",
    "QC Visit Before Inspection",
    "Schedule Concrete Inspection",
    "Check If Windstorm metals Needed",
    "Windstorm Inspection (By RGV Structure)",
    "Make sure foundation has done the sunken showers if needed",
    "Pour Concrete"
  ],
  "Phase 2": [
    "Quote and order Lumber Package",
    "Deliver Lumber Package",
    "Lay Out Framing",
    "Quality Control Visit",
    "Exterior & Interior Wall framing",
    "All showers need to have proper niches built by framer",
    "Ceiling designs must be provided to the framer.",
    "Roof Framing / Sheathing & Fascia",
    "Order Exterior Doors",
    "Deliver Windows",
    "Install Windows",
    "Window / House Wrap",
    "Install Exterior Doors / Frame",
    "Plumbing Rough Before Roof Shingles",
    "Roofing Labor",
    "Framing Punch/ Windstorm Hardware",
    "Quality Control Visit",
    "Verify Windstorm page has shear wall",
    "Schedule Nail Pattern"
  ],
  "Phase 3": [
    "Have selections already been done by the client? If so, add them to the Selections PDF",
    "Bora Care Framing Treatment",
    "Make sure the garage door is ordered if needed",
    "Electrical Rough-In",
    "Plumbing Top Out",
    "A/C Duct Work (Rough HVAC)",
    "Poly Seal",
    "Quality Control Visit",
    "Schedule Inspection If Needed",
    "Wall Insulation",
    "Insulation Inspection",
    "Sheet Rock Material Delivery",
    "Sheet Rock",
    "Exterior Paint"
  ],
  "Phase 4": [
    "Light Fixture Selection (Cristo)",
    "Plumbing Fixture Selection (Cristo)",
    "Tape & Float",
    "Interior/Exterior Rock",
    "Texture",
    "Ceiling Paint (Prime & Finish)"
  ],
  "Phase 5": [
    "Tile Delivery",
    "Flooring Tile",
    "Shower Tile",
    "Schedule the glass and shower door vendor.",
    "Trim, Door, Shelving Installation",
    "Cabinet Installation",
    "Interior Paint",
    "Purchase Counter Tops",
    "Install Counter Tops"
  ],
  "Phase 6": [
    "Install Electrical Fixtures",
    "Plumbing Final Fixtures",
    "InstallMirrors",
    "Install hardware",
    "A/C Compressor & Grills",
    "Final Clean Up",
    "Final Inspection",
    "Owner Walkthrough & Punch List",
    "Certificate of Occupancy (CO) / Final Approval",
    "Punch List Completion"
  ]
};
